=== yrodrigez/letta/src/test/resources/datasets/dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset (user*, event*, assists*)>
<!ELEMENT user EMPTY>
<!ELEMENT event EMPTY>
<!ELEMENT assists EMPTY>
<!ATTLIST user
    login CDATA #REQUIRED
    password CDATA #REQUIRED
>
<!ATTLIST event
    id CDATA #REQUIRED
    title CDATA #REQUIRED
    description CDATA #REQUIRED
    place CDATA #REQUIRED
    num_assistants CDATA #REQUIRED
    start CDATA #REQUIRED
    end CDATA #REQUIRED
    user_id CDATA #REQUIRED
    img CDATA #IMPLIED
    img_ext CDATA #IMPLIED
    category (others|literature|films|sports|tvshows|videogames|programming) "others"
>
<!ATTLIST assists
	user_id CDATA #REQUIRED
	event_id CDATA #REQUIRED
>

=== yrodrigez/letta/src/test/resources/datasets/dataset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">

<dataset>
	<user login="user1" password="11111111111111111111111111111111"/>
	<user login="user2" password="22222222222222222222222222222222"/>
	<user login="user3" password="33333333333333333333333333333333"/>
	<user login="user4" password="44444444444444444444444444444444"/>
	<user login="user5" password="55555555555555555555555555555555"/>
	
	<event num_assistants="10" id="1" start="2012-10-01 20:00:00" place="Ourense" end="2012-10-01 23:00:00" title="Event1" description="Foo description 1" user_id="user1"/>
	<event num_assistants="9" id="2" start="2012-10-02 20:00:00" place="Verín" end="2012-10-02 23:00:00" title="Event2" description="Foo description 2" user_id="user1"/>
	<event num_assistants="100" id="3" start="2012-10-03 20:00:00" place="Marín" end="2012-10-03 23:00:00" title="Event3" description="Foo description 3" user_id="user2"/>
	<event num_assistants="8" id="4" start="2012-10-04 20:00:00" place="Bueu" end="2012-10-04 23:00:00" title="Event4" description="Foo description 4" user_id="user2"/>
	<event num_assistants="15" id="5" start="2012-10-05 20:00:00" place="Castro" end="2012-10-05 23:00:00" title="Event5" description="Foo description 5" user_id="user2"/>
	<event num_assistants="20" id="6" start="2012-10-06 20:00:00" place="Moaña" end="2012-10-06 23:00:00" title="Event6" description="Foo description 6" user_id="user3"/>
	<event num_assistants="30" id="7" start="2012-10-07 20:00:00" place="Pontevedra" end="2012-10-07 23:00:00" title="Event7" description="Foo description 7" user_id="user5"/>
	<event num_assistants="18" id="8" start="2012-10-08 20:00:00" place="Cuntis" end="2012-10-08 23:00:00" title="Event8" description="Foo description 8" user_id="user5"/>
	
	<assists user_id="user1" event_id="3"/>
	<assists user_id="user2" event_id="1"/>
	<assists user_id="user2" event_id="2"/>
	<assists user_id="user4" event_id="3"/>
	<assists user_id="user4" event_id="4"/>
	<assists user_id="user4" event_id="5"/>
	<assists user_id="user5" event_id="3"/>
</dataset>
